# Generated by Django 3.0 on 2021-05-18 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(default=None, max_length=15, null=True)),
                ('Carpickup_date', models.DateTimeField(blank=True)),
                ('Cardropoff_date', models.DateTimeField(blank=True)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('drop_off_location', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(default='XXXX', max_length=50)),
                ('customer_last_name', models.CharField(default='XXXX', max_length=50)),
                ('email', models.CharField(default='test@gmail.com', max_length=50, unique=True)),
                ('phone_number', models.CharField(default=None, max_length=15, null=True)),
                ('address', models.CharField(default='XXXX', max_length=200)),
                ('city', models.CharField(default='XXXX', max_length=100)),
                ('pickup_date', models.DateField(default=django.utils.timezone.now)),
                ('dropoff_date', models.DateField(default=django.utils.timezone.now)),
                ('select_time', models.TimeField(default=django.utils.timezone.now)),
                ('pick_up_location', models.CharField(max_length=100)),
                ('drop_off_location', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car')),
            ],
        ),
    ]
