# Generated by Django 3.0 on 2021-05-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_carbooking_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbooking',
            name='name',
        ),
    ]
