# Generated by Django 3.0 on 2021-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_carbooking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
