# Generated by Django 3.0 on 2021-05-04 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cartype', models.CharField(choices=[('Sports Car', 'Sports Car'), ('Luxury Sedan', 'Luxury Sedan'), ('Hatchback', 'Hatchback'), ('MPV', 'MPV'), ('SUV', 'SUV'), ('Hybrid Car', 'Hybrid Car'), ('Electric Car', 'Electric Car')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(choices=[('Kuala Lumpur', 'Kuala Lumpur'), ('Selangor', 'Selangor'), ('Pahang', 'Pahang'), ('Perak', 'Perak')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(choices=[('KL Sentral', 'KL Sentral'), ('KLCC', 'KLCC'), ('Masjid Jamek', 'Masjid Jamek'), ('Kajang', 'Kajang'), ('Bangi', 'Bangi'), ('Brinchang', 'Brinchang'), ('Tanah Rata', 'Tanah Rata'), ('Lumut', 'Lumut'), ('Ipoh', 'Ipoh')], max_length=50)),
                ('Statename', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.State')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('image_main', models.ImageField(upload_to='images')),
                ('image1', models.ImageField(blank=True, upload_to='images')),
                ('image2', models.ImageField(blank=True, upload_to='images')),
                ('image3', models.ImageField(blank=True, upload_to='images')),
                ('image4', models.ImageField(blank=True, upload_to='images')),
                ('image5', models.ImageField(blank=True, upload_to='images')),
                ('miles', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50)),
                ('year', models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='year')),
                ('car_engine_size', models.CharField(choices=[('1.6cc', '1.6cc'), ('1.8cc', '1.8cc'), ('2.0cc', '2.0cc'), ('3.0cc', '3.0cc'), ('4.0cc', '4.0cc')], default='1.6cc', max_length=50)),
                ('power', models.IntegerField()),
                ('fuel', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('availablity', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=50)),
                ('cartype_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.CarType')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.City')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dealers.Dealer')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.State')),
            ],
        ),
    ]
